最初にfulfilledしたPromiseについて処理 race使用

```javascript
const promise1 = new Promise(
  (resolve, reject) => setTimeout(() => resolve(1), 3000)
)

const promise2 = new Promise(
  (resolve, reject) => setTimeout(() => reject('error occurred.'), 2000)
)

const promise3 = new Promise(
  (resolve, reject) => setTimeout(() => resolve(3), 1000)
)
```


```javascript
Promise.race([promise1, promise2, promise3])
.then(result => console.log(result))
.catch(error => console.log(`error: ${error}`))
```


```
> 3
```


全てfulfilledしたPromiseについて処理 all使用

```javascript
const promise1 = new Promise(
  (resolve, reject) => setTimeout(() => resolve(1), 3000)
)

const promise2 = new Promise(
  (resolve, reject) => setTimeout(() => resolve(2), 2000)
)

const promise3 = new Promise(
  (resolve, reject) => setTimeout(() => resolve(3), 1000)
)
```


```javascript
Promise.all([promise1, promise2, promise3])
.then(result => console.log(result))
.catch(error => console.log(`error: ${error}`))
```


```
>  [1, 2, 3]
```


もしどれかrejectedになったら...

```javascript
const promise1 = new Promise(
  (resolve, reject) => setTimeout(() => resolve(1), 3000)
)

const promise2 = new Promise(
  (resolve, reject) => setTimeout(() => reject(2), 2000)
)

const promise3 = new Promise(
  (resolve, reject) => setTimeout(() => resolve(3), 1000)
)
```


```javascript
Promise.all([promise1, promise2, promise3])
.then(result => console.log(result))
.catch(error => console.log(`error: ${error}`))
```


```
> error: 2
```


どれかrejectedされてもfulfilledの結果を使いたい

=>

全てがfulfilled/rejectedしたPromiseについて処理 allSettled使用


```javascript
Promise.allSettled([promise1, promise2, promise3])
.then(result => console.log(result))
```


```
> [
   {status: "fulfilled", value: 1},
   {status: "rejected", reason: 2},
   {status: "fulfilled", value: 3}
  ]
```